spring:
  datasource:
    url:  "jdbc:mysql://localhost:3306/springbootdata?\
    characterEncoding=utf-8&serverTimezone=Asia/Shanghai"
    username: root
    password: 123456

server:
  servlet:
    session:
      timeout: 30m
      tracking-modes: cookie
